In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F 
import torch.optim as optim 

torch.manual_seed(1)

In [2]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
torch.manual_seed(777)
if device == 'cuda':
    torch.cuda.manual_seed_all(777)

In [3]:
X = torch.FloatTensor([[0, 0], 
                       [0, 1], 
                       [1, 0], 
                       [1, 1]]).to(device)
Y = torch.FloatTensor([[0], 
                       [1], 
                       [1], 
                       [0]]).to(device)

In [4]:
linear = nn.Linear(2, 1, bias=True)
sigmoid = nn.Sigmoid()
model = nn.Sequential(linear, sigmoid).to(device)

In [5]:
# 비용 함수와 옵티마이저 정의
criterion = torch.nn.BCELoss().to(device)
optimizer = torch.optim.SGD(model.parameters(), lr=1)

In [6]:
#10,001번의 에포크 수행. 0번 에포크부터 10,000번 에포크까지.
for step in range(10001): 
    optimizer.zero_grad()
    hypothesis = model(X)

    # 비용 함수
    cost = criterion(hypothesis, Y)
    cost.backward()
    optimizer.step()

    if step % 100 == 0: # 100번째 에포크마다 비용 출력
        print(f"STEP: {step:>6,}/10,000, COST: {cost.item():>10.6f}")

STEP:      0/10,000, COST:   0.727397
STEP:    100/10,000, COST:   0.693148
STEP:    200/10,000, COST:   0.693147
STEP:    300/10,000, COST:   0.693147
STEP:    400/10,000, COST:   0.693147
STEP:    500/10,000, COST:   0.693147
STEP:    600/10,000, COST:   0.693147
STEP:    700/10,000, COST:   0.693147
STEP:    800/10,000, COST:   0.693147
STEP:    900/10,000, COST:   0.693147
STEP:  1,000/10,000, COST:   0.693147
STEP:  1,100/10,000, COST:   0.693147
STEP:  1,200/10,000, COST:   0.693147
STEP:  1,300/10,000, COST:   0.693147
STEP:  1,400/10,000, COST:   0.693147
STEP:  1,500/10,000, COST:   0.693147
STEP:  1,600/10,000, COST:   0.693147
STEP:  1,700/10,000, COST:   0.693147
STEP:  1,800/10,000, COST:   0.693147
STEP:  1,900/10,000, COST:   0.693147
STEP:  2,000/10,000, COST:   0.693147
STEP:  2,100/10,000, COST:   0.693147
STEP:  2,200/10,000, COST:   0.693147
STEP:  2,300/10,000, COST:   0.693147
STEP:  2,400/10,000, COST:   0.693147
STEP:  2,500/10,000, COST:   0.693147
STEP:  2,600

In [10]:
with torch.no_grad():
    hypothesis = model(X)
    predicted = (hypothesis > 0.5).float()
    accuracy = (predicted == Y).float().mean()
    print(f'모델의 출력값(Hypothesis):\n{hypothesis.detach().cpu().numpy()}\n\n')
    print(f'모델의 예측값(Predicted):\n{predicted.detach().cpu().numpy()}\n\n')
    print(f'실제값(Y):\n{Y.cpu().numpy()}\n')
    print(f'정확도(Accuracy): {accuracy.item()*100:.4f}%' )

모델의 출력값(Hypothesis):
[[0.5]
 [0.5]
 [0.5]
 [0.5]]


모델의 예측값(Predicted):
[[0.]
 [0.]
 [0.]
 [0.]]


실제값(Y):
[[0.]
 [1.]
 [1.]
 [0.]]

정확도(Accuracy): 50.0000%
