In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F 
import torch.optim as optim 

In [2]:
# setting random seed
torch.manual_seed(1)

In [3]:
# Traning dataset
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

# check shape of Tensors
print(f'x_train is\n{x_train}')
print(f"Shape of x_train: {x_train.shape}")
print()
print(f'y_train is\n{y_train}')
print(f"Shape of y_train: {y_train.shape}")


x_train is
tensor([[1.],
        [2.],
        [3.]])
Shape of x_train: torch.Size([3, 1])

y_train is
tensor([[2.],
        [4.],
        [6.]])
Shape of y_train: torch.Size([3, 1])


In [4]:
# To initialize weights
W = torch.zeros(1, requires_grad=True)
print(f"W = {W}")

W = tensor([0.], requires_grad=True)


In [5]:
# to initialize bias
b = torch.zeros(1, requires_grad=True)
print(f"b = {b}")

b = tensor([0.], requires_grad=True)


In [6]:
# Hypothesis function
hypothesis = x_train  *  W + b 
print(f"hypotheis = \n{hypothesis}")

hypotheis = 
tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [7]:
cost = torch.mean((hypothesis - y_train)**2)
print(f"cost = {cost:2.6f}")
print(cost)

cost = 18.666666
tensor(18.6667, grad_fn=<MeanBackward0>)


In [8]:
optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 2000

for epoch in range(nb_epochs + 1):
    hypothesis = x_train  *  W + b 
    cost = torch.mean((y_train - hypothesis)**2)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print(f"Epoch {epoch:04d}/{nb_epochs}, W: {W.item():.4f}, b: {b.item():.4f}, Cost: {cost.item():013.10f}")
    

Epoch 0000/2000, W: 0.1867, b: 0.0800, Cost: 18.6666660309
Epoch 0100/2000, W: 1.7457, b: 0.5781, Cost: 00.0481706001
Epoch 0200/2000, W: 1.8001, b: 0.4544, Cost: 00.0297665372
Epoch 0300/2000, W: 1.8429, b: 0.3572, Cost: 00.0183939207
Epoch 0400/2000, W: 1.8765, b: 0.2808, Cost: 00.0113663347
Epoch 0500/2000, W: 1.9029, b: 0.2207, Cost: 00.0070236684
Epoch 0600/2000, W: 1.9237, b: 0.1735, Cost: 00.0043401984
Epoch 0700/2000, W: 1.9400, b: 0.1364, Cost: 00.0026819755
Epoch 0800/2000, W: 1.9528, b: 0.1072, Cost: 00.0016572938
Epoch 0900/2000, W: 1.9629, b: 0.0843, Cost: 00.0010241126
Epoch 1000/2000, W: 1.9709, b: 0.0663, Cost: 00.0006328357
Epoch 1100/2000, W: 1.9771, b: 0.0521, Cost: 00.0003910582
Epoch 1200/2000, W: 1.9820, b: 0.0409, Cost: 00.0002416476
Epoch 1300/2000, W: 1.9858, b: 0.0322, Cost: 00.0001493232
Epoch 1400/2000, W: 1.9889, b: 0.0253, Cost: 00.0000922721
Epoch 1500/2000, W: 1.9913, b: 0.0199, Cost: 00.0000570208
Epoch 1600/2000, W: 1.9931, b: 0.0156, Cost: 00.00003523