In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F 
import torch.optim as optim 

torch.manual_seed(1)

In [2]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

# for reproducibility
torch.manual_seed(777)
if device == 'cuda':
    torch.cuda.manual_seed_all(777)

In [3]:
X = torch.FloatTensor([[0, 0], 
                       [0, 1], 
                       [1, 0], 
                       [1, 1]]).to(device)
Y = torch.FloatTensor([[0], 
                       [1], 
                       [1], 
                       [0]]).to(device)

In [4]:
model = nn.Sequential(
          nn.Linear(2, 10, bias=True), # input_layer = 2, hidden_layer1 = 10
          nn.Sigmoid(),
          nn.Linear(10, 10, bias=True), # hidden_layer1 = 10, hidden_layer2 = 10
          nn.Sigmoid(),
          nn.Linear(10, 10, bias=True), # hidden_layer2 = 10, hidden_layer3 = 10
          nn.Sigmoid(),
          nn.Linear(10, 1, bias=True), # hidden_layer3 = 10, output_layer = 1
          nn.Sigmoid()
          ).to(device)

In [5]:
criterion = torch.nn.BCELoss().to(device)
optimizer = torch.optim.SGD(model.parameters(), lr=1)  # modified learning rate from 0.1 to 1

In [8]:
for epoch in range(10001):
    optimizer.zero_grad()
    # forward 연산
    hypothesis = model(X)

    # 비용 함수
    cost = criterion(hypothesis, Y)
    cost.backward()
    optimizer.step()

    # 100의 배수에 해당되는 에포크마다 비용을 출력
    if epoch % 100 == 0:
        print(f"epoch: {epoch:>6,}/10,000, COST: {cost.item():>10.6f}")

epoch:      0/10,000, COST:   0.693158
epoch:    100/10,000, COST:   0.693156
epoch:    200/10,000, COST:   0.693154
epoch:    300/10,000, COST:   0.693151
epoch:    400/10,000, COST:   0.693149
epoch:    500/10,000, COST:   0.693147
epoch:    600/10,000, COST:   0.693145
epoch:    700/10,000, COST:   0.693143
epoch:    800/10,000, COST:   0.693142
epoch:    900/10,000, COST:   0.693140
epoch:  1,000/10,000, COST:   0.693138
epoch:  1,100/10,000, COST:   0.693136
epoch:  1,200/10,000, COST:   0.693134
epoch:  1,300/10,000, COST:   0.693132
epoch:  1,400/10,000, COST:   0.693130
epoch:  1,500/10,000, COST:   0.693128
epoch:  1,600/10,000, COST:   0.693126
epoch:  1,700/10,000, COST:   0.693124
epoch:  1,800/10,000, COST:   0.693122
epoch:  1,900/10,000, COST:   0.693120
epoch:  2,000/10,000, COST:   0.693117
epoch:  2,100/10,000, COST:   0.693114
epoch:  2,200/10,000, COST:   0.693112
epoch:  2,300/10,000, COST:   0.693108
epoch:  2,400/10,000, COST:   0.693105
epoch:  2,500/10,000, COS

In [9]:
with torch.no_grad():
    hypothesis = model(X)
    predicted = (hypothesis > 0.5).float()
    accuracy = (predicted == Y).float().mean()
    print(f'모델의 출력값(Hypothesis):\n{hypothesis.detach().cpu().numpy()}\n\n')
    print(f'모델의 예측값(Predicted):\n{predicted.detach().cpu().numpy()}\n\n')
    print(f'실제값(Y):\n{Y.cpu().numpy()}\n')
    print(f'정확도(Accuracy): {accuracy.item()*100:.4f}%' )

모델의 출력값(Hypothesis):
[[1.1169377e-04]
 [9.9982882e-01]
 [9.9984229e-01]
 [1.8525735e-04]]


모델의 예측값(Predicted):
[[0.]
 [1.]
 [1.]
 [0.]]


실제값(Y):
[[0.]
 [1.]
 [1.]
 [0.]]

정확도(Accuracy): 100.0000%
